services:
  api:
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - "4022:4022"
    volumes:
      - ./logs:/app/logs
    networks:
      - api-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4022/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  logs:

networks:
  api-net:
    driver: bridge