services:
  api:
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - "4022:4022"
    volumes:
      - ./logs:/app/logs
    networks:
      - api-net

volumes:
  logs:

networks:
  api-net:
    driver: bridge