name: Deploy to OCI VM

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ closed ]
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true || github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.OCI_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.OCI_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to OCI VM
        run: |
          ssh ${{ secrets.OCI_USER }}@${{ secrets.OCI_HOST }} "
            cd ~/api || git clone https://github.com/askchimps/api ~/api;
            cd ~/api &&
            git pull &&
            [ -f docker-compose.yml ] && docker-compose down && docker-compose up -d --build
          "